spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:payments}?zeroDateTimeBehavior=convertToNull
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:mysql}
      driver-class-name: com.mysql.cj.jdbc.Driver
  

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: '/payments'
---
